version: "3.7"

volumes:
  www:
  storage:
  pgdata:

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - www:/var/www:ro
    ports:
      - 80:80

  app:
    build: .
    volumes:
      - www:/var/www
      - storage:/var/www/storage

  db:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
