version: "3.7"

volumes:
  pgdata:

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/public:ro

    ports:
      - 80:80

  app:
    build: .
    volumes:
      - ./:/var/www

  db:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
