apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
  {{- range $key, $value := .Values.backend.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
  {{- range $key, $value := .Values.backend.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
