apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 80
  {{- end }}
